eventstore:
  build: docker/eventstore
  command: bash /entrypoint.sh
  volumes:
    - ./data/eventstore:/var/lib/eventstore
    - ./logs/eventstore:/var/log/eventstore
  ports:
    - 2113:2113

write:
  extends:
    file: docker-common.yml
    service: php70
  links:
    - eventstore
  volumes:
    - ./:/var/www
  command: php write.php

read:
  extends:
    file: docker-common.yml
    service: php70
  links:
    - eventstore
  volumes:
    - ./:/var/www
  command: php read.php

subscribe:
  extends:
    file: docker-common.yml
    service: php70
  links:
    - eventstore
  volumes:
    - ./:/var/www
  command: php subscribe.php
